### ISSUE TITLE
Add a default for when user doesn't add valid working intervals

### ISSUE THREAD

**Issue by ilbonte** [danielefongo/toggl-tracker#5]
sulla scelta “workingHoursIntervals” ho erronamente premuto la freccia in giù ed ora nel file di conf trovo "workingHoursIntervals": "" e qua su pick intervals presubilmente strippa
forse ho fatto freccia in giù -> invio
forse dovresti mettere dei default se l’utente non imposta niente

**Comment by ilbonte** [comment]
I can work on this 🚀

**Comment by ilbonte** [comment]
Actually I think that by using the arrow key I deleted the default suggested input so it saved empty intervals. Do you think that  at least one interval should be required or it's optional?

**Comment by danielefongo** [comment]
Interval is required. Maybe we can change the issue to:

> Check input validity on `toggl-tracker config`

If you want, we can work on this together.

**Comment by danielefongo** [comment]
Now all required configurations are checked during the `config` command.
In addition, if the config-file (`.toggl-tracker.json`) is corrupted or contains wrong data, toggl-tracker will prompt a forced setup (maintaining all valid configurations).
