### ISSUE TITLE
Check the last few days

### ISSUE THREAD

**Issue by AlessioCoser** [danielefongo/toggl-tracker#8]
As a user I want to be able to check the last days entered. 

For example with the command: `toggl-tracker check 30` (30 is the interval of days before today)
I would like to see a detailed list of last X days. Each day I would like to see each timeslot with related project I worked.

**Comment by danielefongo** [comment]
Feature released. You can run
```
toggl-tracker check
```

to show entries on the last N days, where N is equal to the look behind days (it is the same the tool uses in other modes)
